package com.dream.myliu.liangwarehouse.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BRAND_INTENT_LOGO_ETY".
 */
public class BrandIntentLogoEty {

    private String url;
    private Long logo_id;

    public BrandIntentLogoEty() {
    }

    public BrandIntentLogoEty(Long logo_id) {
        this.logo_id = logo_id;
    }

    public BrandIntentLogoEty(String url, Long logo_id) {
        this.url = url;
        this.logo_id = logo_id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Long getLogo_id() {
        return logo_id;
    }

    public void setLogo_id(Long logo_id) {
        this.logo_id = logo_id;
    }

}
