package com.dream.myliu.liangwarehouse.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.dream.myliu.liangwarehouse.greendao.BrandItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BRAND_ITEM".
*/
public class BrandItemDao extends AbstractDao<BrandItem, Long> {

    public static final String TABLENAME = "BRAND_ITEM";

    /**
     * Properties of entity BrandItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Description = new Property(0, String.class, "description", false, "DESCRIPTION");
        public final static Property _id_b_it = new Property(1, Long.class, "_id_b_it", true, "_ID_B_IT");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Id = new Property(3, Integer.class, "id", false, "ID");
        public final static Property _id_brand_cate = new Property(4, Long.class, "_id_brand_cate", false, "_ID_BRAND_CATE");
        public final static Property _id_cate_logo = new Property(5, Long.class, "_id_cate_logo", false, "_ID_CATE_LOGO");
    };

    private DaoSession daoSession;

    private Query<BrandItem> brandDataEty_ItemsQuery;

    public BrandItemDao(DaoConfig config) {
        super(config);
    }
    
    public BrandItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BRAND_ITEM\" (" + //
                "\"DESCRIPTION\" TEXT," + // 0: description
                "\"_ID_B_IT\" INTEGER PRIMARY KEY ," + // 1: _id_b_it
                "\"NAME\" TEXT," + // 2: name
                "\"ID\" INTEGER," + // 3: id
                "\"_ID_BRAND_CATE\" INTEGER," + // 4: _id_brand_cate
                "\"_ID_CATE_LOGO\" INTEGER);"); // 5: _id_cate_logo
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BRAND_ITEM\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BrandItem entity) {
        stmt.clearBindings();
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(1, description);
        }
 
        Long _id_b_it = entity.get_id_b_it();
        if (_id_b_it != null) {
            stmt.bindLong(2, _id_b_it);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        Integer id = entity.getId();
        if (id != null) {
            stmt.bindLong(4, id);
        }
 
        Long _id_brand_cate = entity.get_id_brand_cate();
        if (_id_brand_cate != null) {
            stmt.bindLong(5, _id_brand_cate);
        }
 
        Long _id_cate_logo = entity.get_id_cate_logo();
        if (_id_cate_logo != null) {
            stmt.bindLong(6, _id_cate_logo);
        }
    }

    @Override
    protected void attachEntity(BrandItem entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1);
    }    

    /** @inheritdoc */
    @Override
    public BrandItem readEntity(Cursor cursor, int offset) {
        BrandItem entity = new BrandItem( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // description
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // _id_b_it
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // id
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // _id_brand_cate
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // _id_cate_logo
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BrandItem entity, int offset) {
        entity.setDescription(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.set_id_b_it(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setId(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.set_id_brand_cate(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.set_id_cate_logo(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BrandItem entity, long rowId) {
        entity.set_id_b_it(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BrandItem entity) {
        if(entity != null) {
            return entity.get_id_b_it();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "items" to-many relationship of BrandDataEty. */
    public List<BrandItem> _queryBrandDataEty_Items(Long _id_b_it) {
        synchronized (this) {
            if (brandDataEty_ItemsQuery == null) {
                QueryBuilder<BrandItem> queryBuilder = queryBuilder();
                queryBuilder.where(Properties._id_b_it.eq(null));
                brandDataEty_ItemsQuery = queryBuilder.build();
            }
        }
        Query<BrandItem> query = brandDataEty_ItemsQuery.forCurrentThread();
        query.setParameter(0, _id_b_it);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBrandDataEtyDao().getAllColumns());
            builder.append(" FROM BRAND_ITEM T");
            builder.append(" LEFT JOIN BRAND_DATA_ETY T0 ON T.\"_ID_B_IT\"=T0.\"_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected BrandItem loadCurrentDeep(Cursor cursor, boolean lock) {
        BrandItem entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BrandDataEty brandDataEty = loadCurrentOther(daoSession.getBrandDataEtyDao(), cursor, offset);
        entity.setBrandDataEty(brandDataEty);

        return entity;    
    }

    public BrandItem loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<BrandItem> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<BrandItem> list = new ArrayList<BrandItem>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<BrandItem> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<BrandItem> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
