package com.dream.myliu.liangwarehouse.greendao;

import java.util.List;
import com.dream.myliu.liangwarehouse.greendao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BRAND_INTENT_ETY".
 */
public class BrandIntentEty {

    private Long id;
    private String name;
    private Long logo_id;
    private String description;
    private BrandIntentLogoEty logo;

    public BrandIntentLogoEty getLogo() {
        return logo;
    }

    public void setLogo(BrandIntentLogoEty logo) {
        this.logo = logo;
    }

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient BrandIntentEtyDao myDao;

    private List<BrandIntentGoodsEty> goods;

    public BrandIntentEty() {
    }

    public BrandIntentEty(Long id) {
        this.id = id;
    }

    public BrandIntentEty(Long id, String name, Long logo_id, String description) {
        this.id = id;
        this.name = name;
        this.logo_id = logo_id;
        this.description = description;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getBrandIntentEtyDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getLogo_id() {
        return logo_id;
    }

    public void setLogo_id(Long logo_id) {
        this.logo_id = logo_id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<BrandIntentGoodsEty> getGoods() {
        if (goods == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            BrandIntentGoodsEtyDao targetDao = daoSession.getBrandIntentGoodsEtyDao();
            List<BrandIntentGoodsEty> goodsNew = targetDao._queryBrandIntentEty_Goods(id);
            synchronized (this) {
                if(goods == null) {
                    goods = goodsNew;
                }
            }
        }
        return goods;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetGoods() {
        goods = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
