package com.dream.myliu.liangwarehouse.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BRAND_LOGO".
 */
public class BrandLogo {

    private String url;
    private Long _id_cate_logo;

    public BrandLogo() {
    }

    public BrandLogo(Long _id_cate_logo) {
        this._id_cate_logo = _id_cate_logo;
    }

    public BrandLogo(String url, Long _id_cate_logo) {
        this.url = url;
        this._id_cate_logo = _id_cate_logo;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Long get_id_cate_logo() {
        return _id_cate_logo;
    }

    public void set_id_cate_logo(Long _id_cate_logo) {
        this._id_cate_logo = _id_cate_logo;
    }

}
