package com.dream.myliu.liangwarehouse.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.dream.myliu.liangwarehouse.greendao.BrandIntentGoodsImgEty;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BRAND_INTENT_GOODS_IMG_ETY".
*/
public class BrandIntentGoodsImgEtyDao extends AbstractDao<BrandIntentGoodsImgEty, Long> {

    public static final String TABLENAME = "BRAND_INTENT_GOODS_IMG_ETY";

    /**
     * Properties of entity BrandIntentGoodsImgEty.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Url = new Property(0, String.class, "url", false, "URL");
        public final static Property Brand_intent_img_id = new Property(1, Long.class, "brand_intent_img_id", true, "BRAND_INTENT_IMG_ID");
    };

    private DaoSession daoSession;

    private Query<BrandIntentGoodsImgEty> brandIntentGoodsEty_ImagesQuery;

    public BrandIntentGoodsImgEtyDao(DaoConfig config) {
        super(config);
    }
    
    public BrandIntentGoodsImgEtyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BRAND_INTENT_GOODS_IMG_ETY\" (" + //
                "\"URL\" TEXT," + // 0: url
                "\"BRAND_INTENT_IMG_ID\" INTEGER PRIMARY KEY );"); // 1: brand_intent_img_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BRAND_INTENT_GOODS_IMG_ETY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BrandIntentGoodsImgEty entity) {
        stmt.clearBindings();
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(1, url);
        }
 
        Long brand_intent_img_id = entity.getBrand_intent_img_id();
        if (brand_intent_img_id != null) {
            stmt.bindLong(2, brand_intent_img_id);
        }
    }

    @Override
    protected void attachEntity(BrandIntentGoodsImgEty entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1);
    }    

    /** @inheritdoc */
    @Override
    public BrandIntentGoodsImgEty readEntity(Cursor cursor, int offset) {
        BrandIntentGoodsImgEty entity = new BrandIntentGoodsImgEty( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // url
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1) // brand_intent_img_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BrandIntentGoodsImgEty entity, int offset) {
        entity.setUrl(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setBrand_intent_img_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BrandIntentGoodsImgEty entity, long rowId) {
        entity.setBrand_intent_img_id(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BrandIntentGoodsImgEty entity) {
        if(entity != null) {
            return entity.getBrand_intent_img_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "images" to-many relationship of BrandIntentGoodsEty. */
    public List<BrandIntentGoodsImgEty> _queryBrandIntentGoodsEty_Images(Long brand_intent_img_id) {
        synchronized (this) {
            if (brandIntentGoodsEty_ImagesQuery == null) {
                QueryBuilder<BrandIntentGoodsImgEty> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Brand_intent_img_id.eq(null));
                brandIntentGoodsEty_ImagesQuery = queryBuilder.build();
            }
        }
        Query<BrandIntentGoodsImgEty> query = brandIntentGoodsEty_ImagesQuery.forCurrentThread();
        query.setParameter(0, brand_intent_img_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBrandIntentGoodsEtyDao().getAllColumns());
            builder.append(" FROM BRAND_INTENT_GOODS_IMG_ETY T");
            builder.append(" LEFT JOIN BRAND_INTENT_GOODS_ETY T0 ON T.\"BRAND_INTENT_IMG_ID\"=T0.\"BRAND_INTENT_GOODS_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected BrandIntentGoodsImgEty loadCurrentDeep(Cursor cursor, boolean lock) {
        BrandIntentGoodsImgEty entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BrandIntentGoodsEty brandIntentGoodsEty = loadCurrentOther(daoSession.getBrandIntentGoodsEtyDao(), cursor, offset);
        entity.setBrandIntentGoodsEty(brandIntentGoodsEty);

        return entity;    
    }

    public BrandIntentGoodsImgEty loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<BrandIntentGoodsImgEty> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<BrandIntentGoodsImgEty> list = new ArrayList<BrandIntentGoodsImgEty>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<BrandIntentGoodsImgEty> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<BrandIntentGoodsImgEty> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
