package com.dream.myliu.liangwarehouse.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.dream.myliu.liangwarehouse.greendao.CateListDataEty;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CATE_LIST_DATA_ETY".
*/
public class CateListDataEtyDao extends AbstractDao<CateListDataEty, Void> {

    public static final String TABLENAME = "CATE_LIST_DATA_ETY";

    /**
     * Properties of entity CateListDataEty.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Goods_id = new Property(0, String.class, "goods_id", false, "GOODS_ID");
        public final static Property Goods_image = new Property(1, String.class, "goods_image", false, "GOODS_IMAGE");
        public final static Property Goods_name = new Property(2, String.class, "goods_name", false, "GOODS_NAME");
        public final static Property Price = new Property(3, String.class, "price", false, "PRICE");
        public final static Property Owner_id = new Property(4, String.class, "owner_id", false, "OWNER_ID");
        public final static Property Comment_count = new Property(5, String.class, "comment_count", false, "COMMENT_COUNT");
        public final static Property Like_count = new Property(6, String.class, "like_count", false, "LIKE_COUNT");
        public final static Property Liked = new Property(7, String.class, "liked", false, "LIKED");
        public final static Property Sale_by = new Property(8, String.class, "sale_by", false, "SALE_BY");
        public final static Property Goods_url = new Property(9, String.class, "goods_url", false, "GOODS_URL");
        public final static Property Is_gift = new Property(10, String.class, "is_gift", false, "IS_GIFT");
        public final static Property Discount_price = new Property(11, String.class, "discount_price", false, "DISCOUNT_PRICE");
        public final static Property Coupon_flag = new Property(12, String.class, "coupon_flag", false, "COUPON_FLAG");
        public final static Property Promotion_imgurl = new Property(13, String.class, "promotion_imgurl", false, "PROMOTION_IMGURL");
    };


    public CateListDataEtyDao(DaoConfig config) {
        super(config);
    }
    
    public CateListDataEtyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CATE_LIST_DATA_ETY\" (" + //
                "\"GOODS_ID\" TEXT," + // 0: goods_id
                "\"GOODS_IMAGE\" TEXT," + // 1: goods_image
                "\"GOODS_NAME\" TEXT," + // 2: goods_name
                "\"PRICE\" TEXT," + // 3: price
                "\"OWNER_ID\" TEXT," + // 4: owner_id
                "\"COMMENT_COUNT\" TEXT," + // 5: comment_count
                "\"LIKE_COUNT\" TEXT," + // 6: like_count
                "\"LIKED\" TEXT," + // 7: liked
                "\"SALE_BY\" TEXT," + // 8: sale_by
                "\"GOODS_URL\" TEXT," + // 9: goods_url
                "\"IS_GIFT\" TEXT," + // 10: is_gift
                "\"DISCOUNT_PRICE\" TEXT," + // 11: discount_price
                "\"COUPON_FLAG\" TEXT," + // 12: coupon_flag
                "\"PROMOTION_IMGURL\" TEXT);"); // 13: promotion_imgurl
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CATE_LIST_DATA_ETY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CateListDataEty entity) {
        stmt.clearBindings();
 
        String goods_id = entity.getGoods_id();
        if (goods_id != null) {
            stmt.bindString(1, goods_id);
        }
 
        String goods_image = entity.getGoods_image();
        if (goods_image != null) {
            stmt.bindString(2, goods_image);
        }
 
        String goods_name = entity.getGoods_name();
        if (goods_name != null) {
            stmt.bindString(3, goods_name);
        }
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(4, price);
        }
 
        String owner_id = entity.getOwner_id();
        if (owner_id != null) {
            stmt.bindString(5, owner_id);
        }
 
        String comment_count = entity.getComment_count();
        if (comment_count != null) {
            stmt.bindString(6, comment_count);
        }
 
        String like_count = entity.getLike_count();
        if (like_count != null) {
            stmt.bindString(7, like_count);
        }
 
        String liked = entity.getLiked();
        if (liked != null) {
            stmt.bindString(8, liked);
        }
 
        String sale_by = entity.getSale_by();
        if (sale_by != null) {
            stmt.bindString(9, sale_by);
        }
 
        String goods_url = entity.getGoods_url();
        if (goods_url != null) {
            stmt.bindString(10, goods_url);
        }
 
        String is_gift = entity.getIs_gift();
        if (is_gift != null) {
            stmt.bindString(11, is_gift);
        }
 
        String discount_price = entity.getDiscount_price();
        if (discount_price != null) {
            stmt.bindString(12, discount_price);
        }
 
        String coupon_flag = entity.getCoupon_flag();
        if (coupon_flag != null) {
            stmt.bindString(13, coupon_flag);
        }
 
        String promotion_imgurl = entity.getPromotion_imgurl();
        if (promotion_imgurl != null) {
            stmt.bindString(14, promotion_imgurl);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public CateListDataEty readEntity(Cursor cursor, int offset) {
        CateListDataEty entity = new CateListDataEty( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // goods_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // goods_image
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // goods_name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // price
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // owner_id
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // comment_count
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // like_count
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // liked
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // sale_by
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // goods_url
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // is_gift
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // discount_price
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // coupon_flag
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13) // promotion_imgurl
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CateListDataEty entity, int offset) {
        entity.setGoods_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setGoods_image(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setGoods_name(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPrice(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setOwner_id(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setComment_count(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setLike_count(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setLiked(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setSale_by(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setGoods_url(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setIs_gift(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setDiscount_price(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setCoupon_flag(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setPromotion_imgurl(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(CateListDataEty entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(CateListDataEty entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
