package com.dream.myliu.liangwarehouse.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.List;

/**
 * Entity mapped to table "CATE_DET_DATA_ETY".
 */
public class CateDetDataEty {

    private String goods_id;
    private String goods_image;
    private String goods_url;
    private String goods_name;
    private String goods_desc;
    private String price;
    private String comment_count;
    private String like_count;
    private Integer liked;
    private String discount_price;
    private Boolean coupon_flag;
    private Integer owner_id;
    private String owner_name;
    private String owner_desc;
    private String is_daren;
    private String owner_image;
    private String rec_reason;
    private Integer servicer_id;
    private String category_id;
    private String able_buy_note;
    private Long good_brand_id;
    private Long good_guide_id;
    private List<String> images_item;
    private GoodsGuideEty good_guide;

    private GoodsBrandInfoEty brand_info;

    public GoodsBrandInfoEty getBrand_info() {
        return brand_info;
    }

    public void setBrand_info(GoodsBrandInfoEty brand_info) {
        this.brand_info = brand_info;
    }

    public GoodsGuideEty getGood_guide() {
        return good_guide;
    }

    public void setGood_guide(GoodsGuideEty good_guide) {
        this.good_guide = good_guide;
    }



    public List<String> getImages_item() {
        return images_item;
    }

    public void setImages_item(List<String> images_item) {
        this.images_item = images_item;
    }

    public CateDetDataEty() {
    }

    public CateDetDataEty(String goods_id, String goods_image, String goods_url, String goods_name, String goods_desc, String price, String comment_count, String like_count, Integer liked, String discount_price, Boolean coupon_flag, Integer owner_id, String owner_name, String owner_desc, String is_daren, String owner_image, String rec_reason, Integer servicer_id, String category_id, String able_buy_note, Long good_brand_id, Long good_guide_id) {
        this.goods_id = goods_id;
        this.goods_image = goods_image;
        this.goods_url = goods_url;
        this.goods_name = goods_name;
        this.goods_desc = goods_desc;
        this.price = price;
        this.comment_count = comment_count;
        this.like_count = like_count;
        this.liked = liked;
        this.discount_price = discount_price;
        this.coupon_flag = coupon_flag;
        this.owner_id = owner_id;
        this.owner_name = owner_name;
        this.owner_desc = owner_desc;
        this.is_daren = is_daren;
        this.owner_image = owner_image;
        this.rec_reason = rec_reason;
        this.servicer_id = servicer_id;
        this.category_id = category_id;
        this.able_buy_note = able_buy_note;
        this.good_brand_id = good_brand_id;
        this.good_guide_id = good_guide_id;
    }

    public String getGoods_id() {
        return goods_id;
    }

    public void setGoods_id(String goods_id) {
        this.goods_id = goods_id;
    }

    public String getGoods_image() {
        return goods_image;
    }

    public void setGoods_image(String goods_image) {
        this.goods_image = goods_image;
    }

    public String getGoods_url() {
        return goods_url;
    }

    public void setGoods_url(String goods_url) {
        this.goods_url = goods_url;
    }

    public String getGoods_name() {
        return goods_name;
    }

    public void setGoods_name(String goods_name) {
        this.goods_name = goods_name;
    }

    public String getGoods_desc() {
        return goods_desc;
    }

    public void setGoods_desc(String goods_desc) {
        this.goods_desc = goods_desc;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getComment_count() {
        return comment_count;
    }

    public void setComment_count(String comment_count) {
        this.comment_count = comment_count;
    }

    public String getLike_count() {
        return like_count;
    }

    public void setLike_count(String like_count) {
        this.like_count = like_count;
    }

    public Integer getLiked() {
        return liked;
    }

    public void setLiked(Integer liked) {
        this.liked = liked;
    }

    public String getDiscount_price() {
        return discount_price;
    }

    public void setDiscount_price(String discount_price) {
        this.discount_price = discount_price;
    }

    public Boolean getCoupon_flag() {
        return coupon_flag;
    }

    public void setCoupon_flag(Boolean coupon_flag) {
        this.coupon_flag = coupon_flag;
    }

    public Integer getOwner_id() {
        return owner_id;
    }

    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    public String getOwner_name() {
        return owner_name;
    }

    public void setOwner_name(String owner_name) {
        this.owner_name = owner_name;
    }

    public String getOwner_desc() {
        return owner_desc;
    }

    public void setOwner_desc(String owner_desc) {
        this.owner_desc = owner_desc;
    }

    public String getIs_daren() {
        return is_daren;
    }

    public void setIs_daren(String is_daren) {
        this.is_daren = is_daren;
    }

    public String getOwner_image() {
        return owner_image;
    }

    public void setOwner_image(String owner_image) {
        this.owner_image = owner_image;
    }

    public String getRec_reason() {
        return rec_reason;
    }

    public void setRec_reason(String rec_reason) {
        this.rec_reason = rec_reason;
    }

    public Integer getServicer_id() {
        return servicer_id;
    }

    public void setServicer_id(Integer servicer_id) {
        this.servicer_id = servicer_id;
    }

    public String getCategory_id() {
        return category_id;
    }

    public void setCategory_id(String category_id) {
        this.category_id = category_id;
    }

    public String getAble_buy_note() {
        return able_buy_note;
    }

    public void setAble_buy_note(String able_buy_note) {
        this.able_buy_note = able_buy_note;
    }

    public Long getGood_brand_id() {
        return good_brand_id;
    }

    public void setGood_brand_id(Long good_brand_id) {
        this.good_brand_id = good_brand_id;
    }

    public Long getGood_guide_id() {
        return good_guide_id;
    }

    public void setGood_guide_id(Long good_guide_id) {
        this.good_guide_id = good_guide_id;
    }

}
