package com.dream.myliu.liangwarehouse.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CATE_COVER_ETY".
 */
public class CateCoverEty {

    private String url;
    private Long cover_id;

    public CateCoverEty() {
    }

    public CateCoverEty(Long cover_id) {
        this.cover_id = cover_id;
    }

    public CateCoverEty(String url, Long cover_id) {
        this.url = url;
        this.cover_id = cover_id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Long getCover_id() {
        return cover_id;
    }

    public void setCover_id(Long cover_id) {
        this.cover_id = cover_id;
    }

}
