package com.dream.myliu.liangwarehouse.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dream.myliu.liangwarehouse.greendao.DarenData;
import com.dream.myliu.liangwarehouse.greendao.SearchData;
import com.dream.myliu.liangwarehouse.greendao.DarenPersonDataEty;
import com.dream.myliu.liangwarehouse.greendao.DarenRecmEty;
import com.dream.myliu.liangwarehouse.greendao.CateDataEty;
import com.dream.myliu.liangwarehouse.greendao.CateItemsEty;
import com.dream.myliu.liangwarehouse.greendao.CateCoverEty;
import com.dream.myliu.liangwarehouse.greendao.CateChildEntity;
import com.dream.myliu.liangwarehouse.greendao.SpecilData;
import com.dream.myliu.liangwarehouse.greendao.ShareDataEty;
import com.dream.myliu.liangwarehouse.greendao.BrandDataEty;
import com.dream.myliu.liangwarehouse.greendao.BrandItem;
import com.dream.myliu.liangwarehouse.greendao.BrandLogo;
import com.dream.myliu.liangwarehouse.greendao.BrandCategory;
import com.dream.myliu.liangwarehouse.greendao.CateListDataEty;
import com.dream.myliu.liangwarehouse.greendao.CateDetailEty;
import com.dream.myliu.liangwarehouse.greendao.CateDetDataEty;
import com.dream.myliu.liangwarehouse.greendao.GoodsBrandInfoEty;
import com.dream.myliu.liangwarehouse.greendao.GoodsGuideEty;
import com.dream.myliu.liangwarehouse.greendao.BrandIntentEty;
import com.dream.myliu.liangwarehouse.greendao.BrandIntentLogoEty;
import com.dream.myliu.liangwarehouse.greendao.BrandIntentGoodsEty;
import com.dream.myliu.liangwarehouse.greendao.BrandIntentGoodsImgEty;
import com.dream.myliu.liangwarehouse.greendao.UserGoodsCartEty;
import com.dream.myliu.liangwarehouse.greendao.GoodsOrderEty;

import com.dream.myliu.liangwarehouse.greendao.DarenDataDao;
import com.dream.myliu.liangwarehouse.greendao.SearchDataDao;
import com.dream.myliu.liangwarehouse.greendao.DarenPersonDataEtyDao;
import com.dream.myliu.liangwarehouse.greendao.DarenRecmEtyDao;
import com.dream.myliu.liangwarehouse.greendao.CateDataEtyDao;
import com.dream.myliu.liangwarehouse.greendao.CateItemsEtyDao;
import com.dream.myliu.liangwarehouse.greendao.CateCoverEtyDao;
import com.dream.myliu.liangwarehouse.greendao.CateChildEntityDao;
import com.dream.myliu.liangwarehouse.greendao.SpecilDataDao;
import com.dream.myliu.liangwarehouse.greendao.ShareDataEtyDao;
import com.dream.myliu.liangwarehouse.greendao.BrandDataEtyDao;
import com.dream.myliu.liangwarehouse.greendao.BrandItemDao;
import com.dream.myliu.liangwarehouse.greendao.BrandLogoDao;
import com.dream.myliu.liangwarehouse.greendao.BrandCategoryDao;
import com.dream.myliu.liangwarehouse.greendao.CateListDataEtyDao;
import com.dream.myliu.liangwarehouse.greendao.CateDetailEtyDao;
import com.dream.myliu.liangwarehouse.greendao.CateDetDataEtyDao;
import com.dream.myliu.liangwarehouse.greendao.GoodsBrandInfoEtyDao;
import com.dream.myliu.liangwarehouse.greendao.GoodsGuideEtyDao;
import com.dream.myliu.liangwarehouse.greendao.BrandIntentEtyDao;
import com.dream.myliu.liangwarehouse.greendao.BrandIntentLogoEtyDao;
import com.dream.myliu.liangwarehouse.greendao.BrandIntentGoodsEtyDao;
import com.dream.myliu.liangwarehouse.greendao.BrandIntentGoodsImgEtyDao;
import com.dream.myliu.liangwarehouse.greendao.UserGoodsCartEtyDao;
import com.dream.myliu.liangwarehouse.greendao.GoodsOrderEtyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig darenDataDaoConfig;
    private final DaoConfig searchDataDaoConfig;
    private final DaoConfig darenPersonDataEtyDaoConfig;
    private final DaoConfig darenRecmEtyDaoConfig;
    private final DaoConfig cateDataEtyDaoConfig;
    private final DaoConfig cateItemsEtyDaoConfig;
    private final DaoConfig cateCoverEtyDaoConfig;
    private final DaoConfig cateChildEntityDaoConfig;
    private final DaoConfig specilDataDaoConfig;
    private final DaoConfig shareDataEtyDaoConfig;
    private final DaoConfig brandDataEtyDaoConfig;
    private final DaoConfig brandItemDaoConfig;
    private final DaoConfig brandLogoDaoConfig;
    private final DaoConfig brandCategoryDaoConfig;
    private final DaoConfig cateListDataEtyDaoConfig;
    private final DaoConfig cateDetailEtyDaoConfig;
    private final DaoConfig cateDetDataEtyDaoConfig;
    private final DaoConfig goodsBrandInfoEtyDaoConfig;
    private final DaoConfig goodsGuideEtyDaoConfig;
    private final DaoConfig brandIntentEtyDaoConfig;
    private final DaoConfig brandIntentLogoEtyDaoConfig;
    private final DaoConfig brandIntentGoodsEtyDaoConfig;
    private final DaoConfig brandIntentGoodsImgEtyDaoConfig;
    private final DaoConfig userGoodsCartEtyDaoConfig;
    private final DaoConfig goodsOrderEtyDaoConfig;

    private final DarenDataDao darenDataDao;
    private final SearchDataDao searchDataDao;
    private final DarenPersonDataEtyDao darenPersonDataEtyDao;
    private final DarenRecmEtyDao darenRecmEtyDao;
    private final CateDataEtyDao cateDataEtyDao;
    private final CateItemsEtyDao cateItemsEtyDao;
    private final CateCoverEtyDao cateCoverEtyDao;
    private final CateChildEntityDao cateChildEntityDao;
    private final SpecilDataDao specilDataDao;
    private final ShareDataEtyDao shareDataEtyDao;
    private final BrandDataEtyDao brandDataEtyDao;
    private final BrandItemDao brandItemDao;
    private final BrandLogoDao brandLogoDao;
    private final BrandCategoryDao brandCategoryDao;
    private final CateListDataEtyDao cateListDataEtyDao;
    private final CateDetailEtyDao cateDetailEtyDao;
    private final CateDetDataEtyDao cateDetDataEtyDao;
    private final GoodsBrandInfoEtyDao goodsBrandInfoEtyDao;
    private final GoodsGuideEtyDao goodsGuideEtyDao;
    private final BrandIntentEtyDao brandIntentEtyDao;
    private final BrandIntentLogoEtyDao brandIntentLogoEtyDao;
    private final BrandIntentGoodsEtyDao brandIntentGoodsEtyDao;
    private final BrandIntentGoodsImgEtyDao brandIntentGoodsImgEtyDao;
    private final UserGoodsCartEtyDao userGoodsCartEtyDao;
    private final GoodsOrderEtyDao goodsOrderEtyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        darenDataDaoConfig = daoConfigMap.get(DarenDataDao.class).clone();
        darenDataDaoConfig.initIdentityScope(type);

        searchDataDaoConfig = daoConfigMap.get(SearchDataDao.class).clone();
        searchDataDaoConfig.initIdentityScope(type);

        darenPersonDataEtyDaoConfig = daoConfigMap.get(DarenPersonDataEtyDao.class).clone();
        darenPersonDataEtyDaoConfig.initIdentityScope(type);

        darenRecmEtyDaoConfig = daoConfigMap.get(DarenRecmEtyDao.class).clone();
        darenRecmEtyDaoConfig.initIdentityScope(type);

        cateDataEtyDaoConfig = daoConfigMap.get(CateDataEtyDao.class).clone();
        cateDataEtyDaoConfig.initIdentityScope(type);

        cateItemsEtyDaoConfig = daoConfigMap.get(CateItemsEtyDao.class).clone();
        cateItemsEtyDaoConfig.initIdentityScope(type);

        cateCoverEtyDaoConfig = daoConfigMap.get(CateCoverEtyDao.class).clone();
        cateCoverEtyDaoConfig.initIdentityScope(type);

        cateChildEntityDaoConfig = daoConfigMap.get(CateChildEntityDao.class).clone();
        cateChildEntityDaoConfig.initIdentityScope(type);

        specilDataDaoConfig = daoConfigMap.get(SpecilDataDao.class).clone();
        specilDataDaoConfig.initIdentityScope(type);

        shareDataEtyDaoConfig = daoConfigMap.get(ShareDataEtyDao.class).clone();
        shareDataEtyDaoConfig.initIdentityScope(type);

        brandDataEtyDaoConfig = daoConfigMap.get(BrandDataEtyDao.class).clone();
        brandDataEtyDaoConfig.initIdentityScope(type);

        brandItemDaoConfig = daoConfigMap.get(BrandItemDao.class).clone();
        brandItemDaoConfig.initIdentityScope(type);

        brandLogoDaoConfig = daoConfigMap.get(BrandLogoDao.class).clone();
        brandLogoDaoConfig.initIdentityScope(type);

        brandCategoryDaoConfig = daoConfigMap.get(BrandCategoryDao.class).clone();
        brandCategoryDaoConfig.initIdentityScope(type);

        cateListDataEtyDaoConfig = daoConfigMap.get(CateListDataEtyDao.class).clone();
        cateListDataEtyDaoConfig.initIdentityScope(type);

        cateDetailEtyDaoConfig = daoConfigMap.get(CateDetailEtyDao.class).clone();
        cateDetailEtyDaoConfig.initIdentityScope(type);

        cateDetDataEtyDaoConfig = daoConfigMap.get(CateDetDataEtyDao.class).clone();
        cateDetDataEtyDaoConfig.initIdentityScope(type);

        goodsBrandInfoEtyDaoConfig = daoConfigMap.get(GoodsBrandInfoEtyDao.class).clone();
        goodsBrandInfoEtyDaoConfig.initIdentityScope(type);

        goodsGuideEtyDaoConfig = daoConfigMap.get(GoodsGuideEtyDao.class).clone();
        goodsGuideEtyDaoConfig.initIdentityScope(type);

        brandIntentEtyDaoConfig = daoConfigMap.get(BrandIntentEtyDao.class).clone();
        brandIntentEtyDaoConfig.initIdentityScope(type);

        brandIntentLogoEtyDaoConfig = daoConfigMap.get(BrandIntentLogoEtyDao.class).clone();
        brandIntentLogoEtyDaoConfig.initIdentityScope(type);

        brandIntentGoodsEtyDaoConfig = daoConfigMap.get(BrandIntentGoodsEtyDao.class).clone();
        brandIntentGoodsEtyDaoConfig.initIdentityScope(type);

        brandIntentGoodsImgEtyDaoConfig = daoConfigMap.get(BrandIntentGoodsImgEtyDao.class).clone();
        brandIntentGoodsImgEtyDaoConfig.initIdentityScope(type);

        userGoodsCartEtyDaoConfig = daoConfigMap.get(UserGoodsCartEtyDao.class).clone();
        userGoodsCartEtyDaoConfig.initIdentityScope(type);

        goodsOrderEtyDaoConfig = daoConfigMap.get(GoodsOrderEtyDao.class).clone();
        goodsOrderEtyDaoConfig.initIdentityScope(type);

        darenDataDao = new DarenDataDao(darenDataDaoConfig, this);
        searchDataDao = new SearchDataDao(searchDataDaoConfig, this);
        darenPersonDataEtyDao = new DarenPersonDataEtyDao(darenPersonDataEtyDaoConfig, this);
        darenRecmEtyDao = new DarenRecmEtyDao(darenRecmEtyDaoConfig, this);
        cateDataEtyDao = new CateDataEtyDao(cateDataEtyDaoConfig, this);
        cateItemsEtyDao = new CateItemsEtyDao(cateItemsEtyDaoConfig, this);
        cateCoverEtyDao = new CateCoverEtyDao(cateCoverEtyDaoConfig, this);
        cateChildEntityDao = new CateChildEntityDao(cateChildEntityDaoConfig, this);
        specilDataDao = new SpecilDataDao(specilDataDaoConfig, this);
        shareDataEtyDao = new ShareDataEtyDao(shareDataEtyDaoConfig, this);
        brandDataEtyDao = new BrandDataEtyDao(brandDataEtyDaoConfig, this);
        brandItemDao = new BrandItemDao(brandItemDaoConfig, this);
        brandLogoDao = new BrandLogoDao(brandLogoDaoConfig, this);
        brandCategoryDao = new BrandCategoryDao(brandCategoryDaoConfig, this);
        cateListDataEtyDao = new CateListDataEtyDao(cateListDataEtyDaoConfig, this);
        cateDetailEtyDao = new CateDetailEtyDao(cateDetailEtyDaoConfig, this);
        cateDetDataEtyDao = new CateDetDataEtyDao(cateDetDataEtyDaoConfig, this);
        goodsBrandInfoEtyDao = new GoodsBrandInfoEtyDao(goodsBrandInfoEtyDaoConfig, this);
        goodsGuideEtyDao = new GoodsGuideEtyDao(goodsGuideEtyDaoConfig, this);
        brandIntentEtyDao = new BrandIntentEtyDao(brandIntentEtyDaoConfig, this);
        brandIntentLogoEtyDao = new BrandIntentLogoEtyDao(brandIntentLogoEtyDaoConfig, this);
        brandIntentGoodsEtyDao = new BrandIntentGoodsEtyDao(brandIntentGoodsEtyDaoConfig, this);
        brandIntentGoodsImgEtyDao = new BrandIntentGoodsImgEtyDao(brandIntentGoodsImgEtyDaoConfig, this);
        userGoodsCartEtyDao = new UserGoodsCartEtyDao(userGoodsCartEtyDaoConfig, this);
        goodsOrderEtyDao = new GoodsOrderEtyDao(goodsOrderEtyDaoConfig, this);

        registerDao(DarenData.class, darenDataDao);
        registerDao(SearchData.class, searchDataDao);
        registerDao(DarenPersonDataEty.class, darenPersonDataEtyDao);
        registerDao(DarenRecmEty.class, darenRecmEtyDao);
        registerDao(CateDataEty.class, cateDataEtyDao);
        registerDao(CateItemsEty.class, cateItemsEtyDao);
        registerDao(CateCoverEty.class, cateCoverEtyDao);
        registerDao(CateChildEntity.class, cateChildEntityDao);
        registerDao(SpecilData.class, specilDataDao);
        registerDao(ShareDataEty.class, shareDataEtyDao);
        registerDao(BrandDataEty.class, brandDataEtyDao);
        registerDao(BrandItem.class, brandItemDao);
        registerDao(BrandLogo.class, brandLogoDao);
        registerDao(BrandCategory.class, brandCategoryDao);
        registerDao(CateListDataEty.class, cateListDataEtyDao);
        registerDao(CateDetailEty.class, cateDetailEtyDao);
        registerDao(CateDetDataEty.class, cateDetDataEtyDao);
        registerDao(GoodsBrandInfoEty.class, goodsBrandInfoEtyDao);
        registerDao(GoodsGuideEty.class, goodsGuideEtyDao);
        registerDao(BrandIntentEty.class, brandIntentEtyDao);
        registerDao(BrandIntentLogoEty.class, brandIntentLogoEtyDao);
        registerDao(BrandIntentGoodsEty.class, brandIntentGoodsEtyDao);
        registerDao(BrandIntentGoodsImgEty.class, brandIntentGoodsImgEtyDao);
        registerDao(UserGoodsCartEty.class, userGoodsCartEtyDao);
        registerDao(GoodsOrderEty.class, goodsOrderEtyDao);
    }
    
    public void clear() {
        darenDataDaoConfig.getIdentityScope().clear();
        searchDataDaoConfig.getIdentityScope().clear();
        darenPersonDataEtyDaoConfig.getIdentityScope().clear();
        darenRecmEtyDaoConfig.getIdentityScope().clear();
        cateDataEtyDaoConfig.getIdentityScope().clear();
        cateItemsEtyDaoConfig.getIdentityScope().clear();
        cateCoverEtyDaoConfig.getIdentityScope().clear();
        cateChildEntityDaoConfig.getIdentityScope().clear();
        specilDataDaoConfig.getIdentityScope().clear();
        shareDataEtyDaoConfig.getIdentityScope().clear();
        brandDataEtyDaoConfig.getIdentityScope().clear();
        brandItemDaoConfig.getIdentityScope().clear();
        brandLogoDaoConfig.getIdentityScope().clear();
        brandCategoryDaoConfig.getIdentityScope().clear();
        cateListDataEtyDaoConfig.getIdentityScope().clear();
        cateDetailEtyDaoConfig.getIdentityScope().clear();
        cateDetDataEtyDaoConfig.getIdentityScope().clear();
        goodsBrandInfoEtyDaoConfig.getIdentityScope().clear();
        goodsGuideEtyDaoConfig.getIdentityScope().clear();
        brandIntentEtyDaoConfig.getIdentityScope().clear();
        brandIntentLogoEtyDaoConfig.getIdentityScope().clear();
        brandIntentGoodsEtyDaoConfig.getIdentityScope().clear();
        brandIntentGoodsImgEtyDaoConfig.getIdentityScope().clear();
        userGoodsCartEtyDaoConfig.getIdentityScope().clear();
        goodsOrderEtyDaoConfig.getIdentityScope().clear();
    }

    public DarenDataDao getDarenDataDao() {
        return darenDataDao;
    }

    public SearchDataDao getSearchDataDao() {
        return searchDataDao;
    }

    public DarenPersonDataEtyDao getDarenPersonDataEtyDao() {
        return darenPersonDataEtyDao;
    }

    public DarenRecmEtyDao getDarenRecmEtyDao() {
        return darenRecmEtyDao;
    }

    public CateDataEtyDao getCateDataEtyDao() {
        return cateDataEtyDao;
    }

    public CateItemsEtyDao getCateItemsEtyDao() {
        return cateItemsEtyDao;
    }

    public CateCoverEtyDao getCateCoverEtyDao() {
        return cateCoverEtyDao;
    }

    public CateChildEntityDao getCateChildEntityDao() {
        return cateChildEntityDao;
    }

    public SpecilDataDao getSpecilDataDao() {
        return specilDataDao;
    }

    public ShareDataEtyDao getShareDataEtyDao() {
        return shareDataEtyDao;
    }

    public BrandDataEtyDao getBrandDataEtyDao() {
        return brandDataEtyDao;
    }

    public BrandItemDao getBrandItemDao() {
        return brandItemDao;
    }

    public BrandLogoDao getBrandLogoDao() {
        return brandLogoDao;
    }

    public BrandCategoryDao getBrandCategoryDao() {
        return brandCategoryDao;
    }

    public CateListDataEtyDao getCateListDataEtyDao() {
        return cateListDataEtyDao;
    }

    public CateDetailEtyDao getCateDetailEtyDao() {
        return cateDetailEtyDao;
    }

    public CateDetDataEtyDao getCateDetDataEtyDao() {
        return cateDetDataEtyDao;
    }

    public GoodsBrandInfoEtyDao getGoodsBrandInfoEtyDao() {
        return goodsBrandInfoEtyDao;
    }

    public GoodsGuideEtyDao getGoodsGuideEtyDao() {
        return goodsGuideEtyDao;
    }

    public BrandIntentEtyDao getBrandIntentEtyDao() {
        return brandIntentEtyDao;
    }

    public BrandIntentLogoEtyDao getBrandIntentLogoEtyDao() {
        return brandIntentLogoEtyDao;
    }

    public BrandIntentGoodsEtyDao getBrandIntentGoodsEtyDao() {
        return brandIntentGoodsEtyDao;
    }

    public BrandIntentGoodsImgEtyDao getBrandIntentGoodsImgEtyDao() {
        return brandIntentGoodsImgEtyDao;
    }

    public UserGoodsCartEtyDao getUserGoodsCartEtyDao() {
        return userGoodsCartEtyDao;
    }

    public GoodsOrderEtyDao getGoodsOrderEtyDao() {
        return goodsOrderEtyDao;
    }

}
