package com.dream.myliu.liangwarehouse.greendao;

import java.util.List;
import com.dream.myliu.liangwarehouse.greendao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DAREN_PERSON_DATA_ETY".
 */
public class DarenPersonDataEty {

    private String user_id;
    private String user_name;
    private String is_daren;
    private String email;
    private String user_image;
    private String user_desc;
    private Integer friend;
    private String like_count;
    private String recommendation_count;
    private String following_count;
    private String followed_count;
    private String template_id;
    private Long _id_daren;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient DarenPersonDataEtyDao myDao;

    private List<DarenRecmEty> goods;

    public DarenPersonDataEty() {
    }

    public DarenPersonDataEty(Long _id_daren) {
        this._id_daren = _id_daren;
    }

    public DarenPersonDataEty(String user_id, String user_name, String is_daren, String email, String user_image, String user_desc, Integer friend, String like_count, String recommendation_count, String following_count, String followed_count, String template_id, Long _id_daren) {
        this.user_id = user_id;
        this.user_name = user_name;
        this.is_daren = is_daren;
        this.email = email;
        this.user_image = user_image;
        this.user_desc = user_desc;
        this.friend = friend;
        this.like_count = like_count;
        this.recommendation_count = recommendation_count;
        this.following_count = following_count;
        this.followed_count = followed_count;
        this.template_id = template_id;
        this._id_daren = _id_daren;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getDarenPersonDataEtyDao() : null;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public String getIs_daren() {
        return is_daren;
    }

    public void setIs_daren(String is_daren) {
        this.is_daren = is_daren;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUser_image() {
        return user_image;
    }

    public void setUser_image(String user_image) {
        this.user_image = user_image;
    }

    public String getUser_desc() {
        return user_desc;
    }

    public void setUser_desc(String user_desc) {
        this.user_desc = user_desc;
    }

    public Integer getFriend() {
        return friend;
    }

    public void setFriend(Integer friend) {
        this.friend = friend;
    }

    public String getLike_count() {
        return like_count;
    }

    public void setLike_count(String like_count) {
        this.like_count = like_count;
    }

    public String getRecommendation_count() {
        return recommendation_count;
    }

    public void setRecommendation_count(String recommendation_count) {
        this.recommendation_count = recommendation_count;
    }

    public String getFollowing_count() {
        return following_count;
    }

    public void setFollowing_count(String following_count) {
        this.following_count = following_count;
    }

    public String getFollowed_count() {
        return followed_count;
    }

    public void setFollowed_count(String followed_count) {
        this.followed_count = followed_count;
    }

    public String getTemplate_id() {
        return template_id;
    }

    public void setTemplate_id(String template_id) {
        this.template_id = template_id;
    }

    public Long get_id_daren() {
        return _id_daren;
    }

    public void set_id_daren(Long _id_daren) {
        this._id_daren = _id_daren;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<DarenRecmEty> getGoods() {
        if (goods == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            DarenRecmEtyDao targetDao = daoSession.getDarenRecmEtyDao();
            List<DarenRecmEty> goodsNew = targetDao._queryDarenPersonDataEty_Goods(_id_daren);
            synchronized (this) {
                if(goods == null) {
                    goods = goodsNew;
                }
            }
        }
        return goods;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetGoods() {
        goods = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
