package com.dream.myliu.liangwarehouse.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DAREN_DATA".
 */
public class DarenData {

    private Long _id;
    private String user_id;
    private String user_name;
    private String is_daren;
    private String user_image;
    private String user_desc;

    public DarenData() {
    }

    public DarenData(Long _id) {
        this._id = _id;
    }

    public DarenData(Long _id, String user_id, String user_name, String is_daren, String user_image, String user_desc) {
        this._id = _id;
        this.user_id = user_id;
        this.user_name = user_name;
        this.is_daren = is_daren;
        this.user_image = user_image;
        this.user_desc = user_desc;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public String getIs_daren() {
        return is_daren;
    }

    public void setIs_daren(String is_daren) {
        this.is_daren = is_daren;
    }

    public String getUser_image() {
        return user_image;
    }

    public void setUser_image(String user_image) {
        this.user_image = user_image;
    }

    public String getUser_desc() {
        return user_desc;
    }

    public void setUser_desc(String user_desc) {
        this.user_desc = user_desc;
    }

}
