package com.dream.myliu.liangwarehouse.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GOODS_BRAND_INFO_ETY".
 */
public class GoodsBrandInfoEty {

    private String brand_id;
    private String brand_name;
    private String brand_desc;
    private String brand_logo;
    private Long good_brand_id;

    public GoodsBrandInfoEty() {
    }

    public GoodsBrandInfoEty(Long good_brand_id) {
        this.good_brand_id = good_brand_id;
    }

    public GoodsBrandInfoEty(String brand_id, String brand_name, String brand_desc, String brand_logo, Long good_brand_id) {
        this.brand_id = brand_id;
        this.brand_name = brand_name;
        this.brand_desc = brand_desc;
        this.brand_logo = brand_logo;
        this.good_brand_id = good_brand_id;
    }

    public String getBrand_id() {
        return brand_id;
    }

    public void setBrand_id(String brand_id) {
        this.brand_id = brand_id;
    }

    public String getBrand_name() {
        return brand_name;
    }

    public void setBrand_name(String brand_name) {
        this.brand_name = brand_name;
    }

    public String getBrand_desc() {
        return brand_desc;
    }

    public void setBrand_desc(String brand_desc) {
        this.brand_desc = brand_desc;
    }

    public String getBrand_logo() {
        return brand_logo;
    }

    public void setBrand_logo(String brand_logo) {
        this.brand_logo = brand_logo;
    }

    public Long getGood_brand_id() {
        return good_brand_id;
    }

    public void setGood_brand_id(Long good_brand_id) {
        this.good_brand_id = good_brand_id;
    }

}
