package com.dream.myliu.liangwarehouse.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.dream.myliu.liangwarehouse.greendao.GoodsBrandInfoEty;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GOODS_BRAND_INFO_ETY".
*/
public class GoodsBrandInfoEtyDao extends AbstractDao<GoodsBrandInfoEty, Long> {

    public static final String TABLENAME = "GOODS_BRAND_INFO_ETY";

    /**
     * Properties of entity GoodsBrandInfoEty.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Brand_id = new Property(0, String.class, "brand_id", false, "BRAND_ID");
        public final static Property Brand_name = new Property(1, String.class, "brand_name", false, "BRAND_NAME");
        public final static Property Brand_desc = new Property(2, String.class, "brand_desc", false, "BRAND_DESC");
        public final static Property Brand_logo = new Property(3, String.class, "brand_logo", false, "BRAND_LOGO");
        public final static Property Good_brand_id = new Property(4, Long.class, "good_brand_id", true, "GOOD_BRAND_ID");
    };


    public GoodsBrandInfoEtyDao(DaoConfig config) {
        super(config);
    }
    
    public GoodsBrandInfoEtyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GOODS_BRAND_INFO_ETY\" (" + //
                "\"BRAND_ID\" TEXT," + // 0: brand_id
                "\"BRAND_NAME\" TEXT," + // 1: brand_name
                "\"BRAND_DESC\" TEXT," + // 2: brand_desc
                "\"BRAND_LOGO\" TEXT," + // 3: brand_logo
                "\"GOOD_BRAND_ID\" INTEGER PRIMARY KEY );"); // 4: good_brand_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GOODS_BRAND_INFO_ETY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GoodsBrandInfoEty entity) {
        stmt.clearBindings();
 
        String brand_id = entity.getBrand_id();
        if (brand_id != null) {
            stmt.bindString(1, brand_id);
        }
 
        String brand_name = entity.getBrand_name();
        if (brand_name != null) {
            stmt.bindString(2, brand_name);
        }
 
        String brand_desc = entity.getBrand_desc();
        if (brand_desc != null) {
            stmt.bindString(3, brand_desc);
        }
 
        String brand_logo = entity.getBrand_logo();
        if (brand_logo != null) {
            stmt.bindString(4, brand_logo);
        }
 
        Long good_brand_id = entity.getGood_brand_id();
        if (good_brand_id != null) {
            stmt.bindLong(5, good_brand_id);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4);
    }    

    /** @inheritdoc */
    @Override
    public GoodsBrandInfoEty readEntity(Cursor cursor, int offset) {
        GoodsBrandInfoEty entity = new GoodsBrandInfoEty( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // brand_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // brand_name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // brand_desc
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // brand_logo
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // good_brand_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GoodsBrandInfoEty entity, int offset) {
        entity.setBrand_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setBrand_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBrand_desc(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBrand_logo(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGood_brand_id(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GoodsBrandInfoEty entity, long rowId) {
        entity.setGood_brand_id(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GoodsBrandInfoEty entity) {
        if(entity != null) {
            return entity.getGood_brand_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
