package com.dream.myliu.liangwarehouse.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.dream.myliu.liangwarehouse.greendao.SearchData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SEARCH_DATA".
*/
public class SearchDataDao extends AbstractDao<SearchData, Long> {

    public static final String TABLENAME = "SEARCH_DATA";

    /**
     * Properties of entity SearchData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_ID");
        public final static Property Goods_id = new Property(1, String.class, "goods_id", false, "GOODS_ID");
        public final static Property Goods_image = new Property(2, String.class, "goods_image", false, "GOODS_IMAGE");
        public final static Property Goods_name = new Property(3, String.class, "goods_name", false, "GOODS_NAME");
        public final static Property Price = new Property(4, String.class, "price", false, "PRICE");
        public final static Property Owner_id = new Property(5, String.class, "owner_id", false, "OWNER_ID");
        public final static Property Comment_count = new Property(6, String.class, "comment_count", false, "COMMENT_COUNT");
        public final static Property Liked = new Property(7, Integer.class, "liked", false, "LIKED");
        public final static Property Sale_by = new Property(8, String.class, "sale_by", false, "SALE_BY");
        public final static Property Like_count = new Property(9, String.class, "like_count", false, "LIKE_COUNT");
    };


    public SearchDataDao(DaoConfig config) {
        super(config);
    }
    
    public SearchDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SEARCH_DATA\" (" + //
                "\"_ID\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: _id
                "\"GOODS_ID\" TEXT," + // 1: goods_id
                "\"GOODS_IMAGE\" TEXT," + // 2: goods_image
                "\"GOODS_NAME\" TEXT," + // 3: goods_name
                "\"PRICE\" TEXT," + // 4: price
                "\"OWNER_ID\" TEXT," + // 5: owner_id
                "\"COMMENT_COUNT\" TEXT," + // 6: comment_count
                "\"LIKED\" INTEGER," + // 7: liked
                "\"SALE_BY\" TEXT," + // 8: sale_by
                "\"LIKE_COUNT\" TEXT);"); // 9: like_count
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SEARCH_DATA\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SearchData entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String goods_id = entity.getGoods_id();
        if (goods_id != null) {
            stmt.bindString(2, goods_id);
        }
 
        String goods_image = entity.getGoods_image();
        if (goods_image != null) {
            stmt.bindString(3, goods_image);
        }
 
        String goods_name = entity.getGoods_name();
        if (goods_name != null) {
            stmt.bindString(4, goods_name);
        }
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(5, price);
        }
 
        String owner_id = entity.getOwner_id();
        if (owner_id != null) {
            stmt.bindString(6, owner_id);
        }
 
        String comment_count = entity.getComment_count();
        if (comment_count != null) {
            stmt.bindString(7, comment_count);
        }
 
        Integer liked = entity.getLiked();
        if (liked != null) {
            stmt.bindLong(8, liked);
        }
 
        String sale_by = entity.getSale_by();
        if (sale_by != null) {
            stmt.bindString(9, sale_by);
        }
 
        String like_count = entity.getLike_count();
        if (like_count != null) {
            stmt.bindString(10, like_count);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SearchData readEntity(Cursor cursor, int offset) {
        SearchData entity = new SearchData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // goods_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // goods_image
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // goods_name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // price
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // owner_id
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // comment_count
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // liked
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // sale_by
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // like_count
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SearchData entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGoods_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setGoods_image(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGoods_name(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPrice(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setOwner_id(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setComment_count(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setLiked(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setSale_by(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setLike_count(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SearchData entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SearchData entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
