package com.dream.myliu.liangwarehouse.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SHARE_DATA_ETY".
 */
public class ShareDataEty {

    private Long _id_share;
    private String goods_id;
    private String goods_image;
    private String goods_name;
    private Integer price;
    private String owner_id;
    private String comment_count;
    private String like_count;
    private Integer liked;
    private String sale_by;
    private String goods_url;
    private Integer is_gift;
    private Integer discount_price;
    private Boolean coupon_flag;
    private String promotion_imgurl;

    public ShareDataEty() {
    }

    public ShareDataEty(Long _id_share) {
        this._id_share = _id_share;
    }

    public ShareDataEty(Long _id_share, String goods_id, String goods_image, String goods_name, Integer price, String owner_id, String comment_count, String like_count, Integer liked, String sale_by, String goods_url, Integer is_gift, Integer discount_price, Boolean coupon_flag, String promotion_imgurl) {
        this._id_share = _id_share;
        this.goods_id = goods_id;
        this.goods_image = goods_image;
        this.goods_name = goods_name;
        this.price = price;
        this.owner_id = owner_id;
        this.comment_count = comment_count;
        this.like_count = like_count;
        this.liked = liked;
        this.sale_by = sale_by;
        this.goods_url = goods_url;
        this.is_gift = is_gift;
        this.discount_price = discount_price;
        this.coupon_flag = coupon_flag;
        this.promotion_imgurl = promotion_imgurl;
    }

    public Long get_id_share() {
        return _id_share;
    }

    public void set_id_share(Long _id_share) {
        this._id_share = _id_share;
    }

    public String getGoods_id() {
        return goods_id;
    }

    public void setGoods_id(String goods_id) {
        this.goods_id = goods_id;
    }

    public String getGoods_image() {
        return goods_image;
    }

    public void setGoods_image(String goods_image) {
        this.goods_image = goods_image;
    }

    public String getGoods_name() {
        return goods_name;
    }

    public void setGoods_name(String goods_name) {
        this.goods_name = goods_name;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public String getOwner_id() {
        return owner_id;
    }

    public void setOwner_id(String owner_id) {
        this.owner_id = owner_id;
    }

    public String getComment_count() {
        return comment_count;
    }

    public void setComment_count(String comment_count) {
        this.comment_count = comment_count;
    }

    public String getLike_count() {
        return like_count;
    }

    public void setLike_count(String like_count) {
        this.like_count = like_count;
    }

    public Integer getLiked() {
        return liked;
    }

    public void setLiked(Integer liked) {
        this.liked = liked;
    }

    public String getSale_by() {
        return sale_by;
    }

    public void setSale_by(String sale_by) {
        this.sale_by = sale_by;
    }

    public String getGoods_url() {
        return goods_url;
    }

    public void setGoods_url(String goods_url) {
        this.goods_url = goods_url;
    }

    public Integer getIs_gift() {
        return is_gift;
    }

    public void setIs_gift(Integer is_gift) {
        this.is_gift = is_gift;
    }

    public Integer getDiscount_price() {
        return discount_price;
    }

    public void setDiscount_price(Integer discount_price) {
        this.discount_price = discount_price;
    }

    public Boolean getCoupon_flag() {
        return coupon_flag;
    }

    public void setCoupon_flag(Boolean coupon_flag) {
        this.coupon_flag = coupon_flag;
    }

    public String getPromotion_imgurl() {
        return promotion_imgurl;
    }

    public void setPromotion_imgurl(String promotion_imgurl) {
        this.promotion_imgurl = promotion_imgurl;
    }

}
