package com.dream.myliu.liangwarehouse.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SPECIL_DATA".
 */
public class SpecilData {

    private String taid;
    private String topic_name;
    private String cat_id;
    private String author_id;
    private String topic_url;
    private String access_url;
    private String cover_img;
    private String addtime;
    private String is_show_list;
    private String publish_type;
    private String publish_time;
    private String is_published;
    private String cover_img_new;
    private String hit_number;
    private String goods_number;
    private String cat_name;

    public SpecilData() {
    }

    public SpecilData(String taid, String topic_name, String cat_id, String author_id, String topic_url, String access_url, String cover_img, String addtime, String is_show_list, String publish_type, String publish_time, String is_published, String cover_img_new, String hit_number, String goods_number, String cat_name) {
        this.taid = taid;
        this.topic_name = topic_name;
        this.cat_id = cat_id;
        this.author_id = author_id;
        this.topic_url = topic_url;
        this.access_url = access_url;
        this.cover_img = cover_img;
        this.addtime = addtime;
        this.is_show_list = is_show_list;
        this.publish_type = publish_type;
        this.publish_time = publish_time;
        this.is_published = is_published;
        this.cover_img_new = cover_img_new;
        this.hit_number = hit_number;
        this.goods_number = goods_number;
        this.cat_name = cat_name;
    }

    public String getTaid() {
        return taid;
    }

    public void setTaid(String taid) {
        this.taid = taid;
    }

    public String getTopic_name() {
        return topic_name;
    }

    public void setTopic_name(String topic_name) {
        this.topic_name = topic_name;
    }

    public String getCat_id() {
        return cat_id;
    }

    public void setCat_id(String cat_id) {
        this.cat_id = cat_id;
    }

    public String getAuthor_id() {
        return author_id;
    }

    public void setAuthor_id(String author_id) {
        this.author_id = author_id;
    }

    public String getTopic_url() {
        return topic_url;
    }

    public void setTopic_url(String topic_url) {
        this.topic_url = topic_url;
    }

    public String getAccess_url() {
        return access_url;
    }

    public void setAccess_url(String access_url) {
        this.access_url = access_url;
    }

    public String getCover_img() {
        return cover_img;
    }

    public void setCover_img(String cover_img) {
        this.cover_img = cover_img;
    }

    public String getAddtime() {
        return addtime;
    }

    public void setAddtime(String addtime) {
        this.addtime = addtime;
    }

    public String getIs_show_list() {
        return is_show_list;
    }

    public void setIs_show_list(String is_show_list) {
        this.is_show_list = is_show_list;
    }

    public String getPublish_type() {
        return publish_type;
    }

    public void setPublish_type(String publish_type) {
        this.publish_type = publish_type;
    }

    public String getPublish_time() {
        return publish_time;
    }

    public void setPublish_time(String publish_time) {
        this.publish_time = publish_time;
    }

    public String getIs_published() {
        return is_published;
    }

    public void setIs_published(String is_published) {
        this.is_published = is_published;
    }

    public String getCover_img_new() {
        return cover_img_new;
    }

    public void setCover_img_new(String cover_img_new) {
        this.cover_img_new = cover_img_new;
    }

    public String getHit_number() {
        return hit_number;
    }

    public void setHit_number(String hit_number) {
        this.hit_number = hit_number;
    }

    public String getGoods_number() {
        return goods_number;
    }

    public void setGoods_number(String goods_number) {
        this.goods_number = goods_number;
    }

    public String getCat_name() {
        return cat_name;
    }

    public void setCat_name(String cat_name) {
        this.cat_name = cat_name;
    }

}
