package com.dream.myliu.liangwarehouse.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.dream.myliu.liangwarehouse.greendao.UserGoodsCartEty;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_GOODS_CART_ETY".
*/
public class UserGoodsCartEtyDao extends AbstractDao<UserGoodsCartEty, Long> {

    public static final String TABLENAME = "USER_GOODS_CART_ETY";

    /**
     * Properties of entity UserGoodsCartEty.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property User_name = new Property(0, String.class, "user_name", false, "USER_NAME");
        public final static Property Good_name = new Property(1, String.class, "good_name", false, "GOOD_NAME");
        public final static Property Url_img = new Property(2, String.class, "url_img", false, "URL_IMG");
        public final static Property Good_num = new Property(3, Long.class, "good_num", false, "GOOD_NUM");
        public final static Property _id = new Property(4, Long.class, "_id", true, "_ID");
        public final static Property Counts = new Property(5, Long.class, "counts", false, "COUNTS");
        public final static Property IsChecked = new Property(6, Boolean.class, "isChecked", false, "IS_CHECKED");
        public final static Property OnePrice = new Property(7, Float.class, "onePrice", false, "ONE_PRICE");
    };


    public UserGoodsCartEtyDao(DaoConfig config) {
        super(config);
    }
    
    public UserGoodsCartEtyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_GOODS_CART_ETY\" (" + //
                "\"USER_NAME\" TEXT," + // 0: user_name
                "\"GOOD_NAME\" TEXT," + // 1: good_name
                "\"URL_IMG\" TEXT," + // 2: url_img
                "\"GOOD_NUM\" INTEGER," + // 3: good_num
                "\"_ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 4: _id
                "\"COUNTS\" INTEGER," + // 5: counts
                "\"IS_CHECKED\" INTEGER," + // 6: isChecked
                "\"ONE_PRICE\" REAL);"); // 7: onePrice
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_GOODS_CART_ETY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UserGoodsCartEty entity) {
        stmt.clearBindings();
 
        String user_name = entity.getUser_name();
        if (user_name != null) {
            stmt.bindString(1, user_name);
        }
 
        String good_name = entity.getGood_name();
        if (good_name != null) {
            stmt.bindString(2, good_name);
        }
 
        String url_img = entity.getUrl_img();
        if (url_img != null) {
            stmt.bindString(3, url_img);
        }
 
        Long good_num = entity.getGood_num();
        if (good_num != null) {
            stmt.bindLong(4, good_num);
        }
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(5, _id);
        }
 
        Long counts = entity.getCounts();
        if (counts != null) {
            stmt.bindLong(6, counts);
        }
 
        Boolean isChecked = entity.getIsChecked();
        if (isChecked != null) {
            stmt.bindLong(7, isChecked ? 1L: 0L);
        }
 
        Float onePrice = entity.getOnePrice();
        if (onePrice != null) {
            stmt.bindDouble(8, onePrice);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4);
    }    

    /** @inheritdoc */
    @Override
    public UserGoodsCartEty readEntity(Cursor cursor, int offset) {
        UserGoodsCartEty entity = new UserGoodsCartEty( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // user_name
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // good_name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // url_img
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // good_num
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // _id
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // counts
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // isChecked
            cursor.isNull(offset + 7) ? null : cursor.getFloat(offset + 7) // onePrice
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UserGoodsCartEty entity, int offset) {
        entity.setUser_name(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setGood_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUrl_img(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGood_num(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.set_id(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setCounts(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setIsChecked(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setOnePrice(cursor.isNull(offset + 7) ? null : cursor.getFloat(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(UserGoodsCartEty entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(UserGoodsCartEty entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
